apiVersion: tekton.dev/v1beta1
kind: Task
metadata:    
  name: ibm-sit-pod-down
spec:
  params:
    - default: /source
      name: source-dir
      type: string
    - default: 'quay.io/julescheindjou/argocd-cli:v6.0' ( please update )
      name: tools-image
      type: string
  stepTemplate:
    name: ''
    resources: {}
    volumeMounts:
      - mountPath: $(params.source-dir)
        name: source
  steps:
    - env:
        - name: HOME
          value: /home/devops
        - name: ARGOCD_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: gitops-cd-secret
              optional: true
        - name: ARGOCD_PASSWORD_CD
          valueFrom:
            secretKeyRef:
              key: password
              name: gitops-cd-secret
              optional: true
      image: $(params.tools-image)
      name: gitops
      resources: {}
      script: |
        #!/usr/bin/env bash

         argocd login --insecure << Argocd url>>  --username ${ARGOCD_USERNAME}   --password ${ARGOCD_PASSWORD_CD}

          
          

          argocd  app set << sit project namespace>>  --sync-option Prune=false --sync-policy none


          
          

          oc get << sit project namespace>> -n << sit project namespace>> 1>&2
          if  [ $? -eq 0 ]; then
            
          echo "There is not deployment in << sit project namespace>> project namespace"
           exit 0 
          else
           oc scale deploy/curam-apps-curam-consumer -n curam --replicas=0
           oc scale deploy/curam-apps-curam-producer -n << sit project namespace>> --replicas=0
           oc scale deploy/curam-mqserver-curam -n << sit project namespace>> --replicas=0
           oc scale deploy/curam-xmlserver  -n << sit project namespace>> --replicas=0
           oc scale deploy/curam-web -n << sit project namespace>> --replicas=0
          
              
           fi
          
      workingDir: $(params.source-dir)
  volumes:
    - emptyDir: {}
      name: source
