apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  selfLink: >-
    /apis/triggers.tekton.dev/v1alpha1/namespaces/<< update pipeline project namespace>>/<< pipeline prod name>> 
  resourceVersion: '273700745'
  name: gitops-promote-prod 
  labels:
    app: gitops-promote-prod
spec:
  params:
    - description: The git revision
      name: gitrevision
    - description: The git repository url
      name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: gitops-promote-prod-
      spec:
        params:
          - name: git-url
            value: $(tt.params.gitrepositoryurl)
          - name: git-revision
            value: $(tt.params.gitrevision)
        pipelineRef:
          name: gitops-promote-prod (please with the prod pipeline name)
